version: '3.6'

services:

    postgres-demo:
      image: postgres
      container_name: postgres-demo
      # environment:
      #   - POSTGRES_USER=postgres
      #   - POSTGRES_PASSWORD=ste
      #   - POSTGRES_DB=conference_app
      #   - PGUSER=postgres
      # healthcheck:
      #   test: ["CMD-SHELL", "pg_isready -U postgres"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5
      ports:
        - 5432:5432
      volumes:
        - .:/var/lib/my_data
      restart: always
